package repository

import (
	"context"
	"encoding/json"
	"errors"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"

	"github.com/cQu1x/Incident-War-Room/internal/domain/incident"
	"github.com/cQu1x/Incident-War-Room/internal/errs"
)

// uniqueViolation is the PostgreSQL error code for unique constraint violations.
const uniqueViolation = "23505"

// IncidentRepository stores incidents in the "incidents" table.
type IncidentRepository struct {
	db Querier
}

func NewIncidentRepository(db Querier) *IncidentRepository {
	return &IncidentRepository{db: db}
}

// Create inserts a new incident. ID and CreatedAt are generated by the
// database and written back into inc.
//
// The "one active incident per chat" rule is enforced by the partial unique
// index idx_incidents_one_active_per_chat; its violation is translated
// into errs.ErrIncidentAlreadyActive.
func (r *IncidentRepository) Create(ctx context.Context, inc *incident.Incident) error {
	const query = `
		INSERT INTO incidents (title, severity, status, chat_id, topic_id, created_by)
		VALUES ($1, $2, $3, $4, $5, $6)
		RETURNING id, created_at`

	err := r.db.
		QueryRow(ctx, query, inc.Title, inc.Severity, inc.Status, inc.ChatID, inc.TopicID, inc.CreatedBy).
		Scan(&inc.ID, &inc.CreatedAt)
	if err != nil {
		var pgErr *pgconn.PgError
		if errors.As(err, &pgErr) && pgErr.Code == uniqueViolation {
			return errs.ErrIncidentAlreadyActive
		}
		return errs.Wrapf(errs.KindInternal, "repository.Incident.Create", err, "insert incident")
	}

	return nil
}

// GetByID returns the incident with the given ID,
// or errs.ErrIncidentNotFound if it does not exist.
func (r *IncidentRepository) GetByID(ctx context.Context, id uuid.UUID) (*incident.Incident, error) {
	const op = "repository.Incident.GetByID"
	const query = `
		SELECT id, title, severity, status, chat_id, topic_id, created_by, created_at, closed_at, telegraph_urls, report_url
		FROM incidents
		WHERE id = $1`

	inc, err := scanIncident(r.db.QueryRow(ctx, query, id))
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, errs.ErrIncidentNotFound
		}
		return nil, errs.Wrapf(errs.KindInternal, op, err, "select incident")
	}

	return inc, nil
}

// List returns incidents ordered from newest to oldest by creation time.
// When chatID is non-nil, only incidents belonging to that chat are returned.
func (r *IncidentRepository) List(ctx context.Context, chatID *int64) ([]incident.Incident, error) {
	const op = "repository.Incident.List"
	const query = `
		SELECT id, title, severity, status, chat_id, topic_id, created_by, created_at, closed_at, telegraph_urls, report_url
		FROM incidents
		WHERE ($1::bigint IS NULL OR chat_id = $1)
		ORDER BY created_at DESC`

	rows, err := r.db.Query(ctx, query, chatID)
	if err != nil {
		return nil, errs.Wrapf(errs.KindInternal, op, err, "select incidents")
	}

	incidents, err := pgx.CollectRows(rows, func(row pgx.CollectableRow) (incident.Incident, error) {
		inc, err := scanIncident(row)
		if err != nil {
			return incident.Incident{}, err
		}
		return *inc, nil
	})
	if err != nil {
		return nil, errs.Wrapf(errs.KindInternal, op, err, "scan incidents")
	}

	return incidents, nil
}

func (r *IncidentRepository) GetActiveByTopicID(ctx context.Context, chatID, topicID int64) (*incident.Incident, error) {
	const op = "repository.Incident.GetActiveByTopicID"
	const query = `
		SELECT id, title, severity, status, chat_id, topic_id, created_by, created_at, closed_at, telegraph_urls, report_url
		FROM incidents
		WHERE chat_id = $1 AND topic_id = $2 AND status = $3`

	inc, err := scanIncident(r.db.QueryRow(ctx, query, chatID, topicID, incident.StatusActive))
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, errs.ErrNoActiveIncident
		}
		return nil, errs.Wrapf(errs.KindInternal, op, err, "select incident")
	}

	return inc, nil
}

// UpdateSeverity sets a new severity for the incident,
// or returns errs.ErrIncidentNotFound if it does not exist.
func (r *IncidentRepository) UpdateSeverity(ctx context.Context, id uuid.UUID, severity incident.Severity) error {
	const query = `UPDATE incidents SET severity = $2 WHERE id = $1`

	tag, err := r.db.Exec(ctx, query, id, severity)
	if err != nil {
		return errs.Wrapf(errs.KindInternal, "repository.Incident.UpdateSeverity", err, "update incident severity")
	}
	if tag.RowsAffected() == 0 {
		return errs.ErrIncidentNotFound
	}

	return nil
}

func (r *IncidentRepository) UpdateTelegraphURLs(ctx context.Context, id uuid.UUID, telegraphURLs []string) error {
	const op = "repository.Incident.UpdateTelegraphURLs"
	const query = `UPDATE incidents SET telegraph_urls = $2::jsonb WHERE id = $1`

	if telegraphURLs == nil {
		telegraphURLs = []string{}
	}

	urls, err := json.Marshal(telegraphURLs)
	if err != nil {
		return errs.Wrapf(errs.KindInternal, op, err, "marshal telegraph urls")
	}

	tag, err := r.db.Exec(ctx, query, id, string(urls))
	if err != nil {
		return errs.Wrapf(errs.KindInternal, op, err, "update incident telegraph urls")
	}
	if tag.RowsAffected() == 0 {
		return errs.ErrIncidentNotFound
	}

	return nil
}

func (r *IncidentRepository) UpdateReportURL(ctx context.Context, id uuid.UUID, reportURL string) error {
	const op = "repository.Incident.UpdateReportURL"
	const query = `UPDATE incidents SET report_url = $2 WHERE id = $1`

	tag, err := r.db.Exec(ctx, query, id, reportURL)
	if err != nil {
		return errs.Wrapf(errs.KindInternal, op, err, "update incident report url")
	}
	if tag.RowsAffected() == 0 {
		return errs.ErrIncidentNotFound
	}

	return nil
}

// Close marks an active incident as closed and records the closing time.
// Returns errs.ErrIncidentNotFound if the incident does not exist,
// or errs.ErrIncidentAlreadyClosed if it is not active anymore.
func (r *IncidentRepository) Close(ctx context.Context, id uuid.UUID, closedAt time.Time) error {
	const query = `
		UPDATE incidents
		SET status = $2, closed_at = $3
		WHERE id = $1 AND status = $4`

	tag, err := r.db.Exec(ctx, query, id, incident.StatusClosed, closedAt, incident.StatusActive)
	if err != nil {
		return errs.Wrapf(errs.KindInternal, "repository.Incident.Close", err, "close incident")
	}
	if tag.RowsAffected() == 0 {
		if _, err := r.GetByID(ctx, id); err != nil {
			return err
		}
		return errs.ErrIncidentAlreadyClosed
	}

	return nil
}

// Reopen brings a closed incident back to life under a freshly created topic:
// it flips the status back to ACTIVE, clears the closing time and points the
// incident at newTopicID. Returns errs.ErrIncidentNotFound if the incident does
// not exist, errs.ErrIncidentNotClosed if it is not closed, or
// errs.ErrIncidentAlreadyActive if the chat already has an active incident in
// that topic.
func (r *IncidentRepository) Reopen(ctx context.Context, id uuid.UUID, newTopicID int64) error {
	const query = `
		UPDATE incidents
		SET status = $2, closed_at = NULL, topic_id = $3
		WHERE id = $1 AND status = $4`

	tag, err := r.db.Exec(ctx, query, id, incident.StatusActive, newTopicID, incident.StatusClosed)
	if err != nil {
		var pgErr *pgconn.PgError
		if errors.As(err, &pgErr) && pgErr.Code == uniqueViolation {
			return errs.ErrIncidentAlreadyActive
		}
		return errs.Wrapf(errs.KindInternal, "repository.Incident.Reopen", err, "reopen incident")
	}
	if tag.RowsAffected() == 0 {
		if _, err := r.GetByID(ctx, id); err != nil {
			return err
		}
		return errs.ErrIncidentNotClosed
	}

	return nil
}

// scanIncident reads a single incident row in the standard column order:
// id, title, severity, status, chat_id, topic_id, created_by, created_at,
// closed_at, telegraph_urls, report_url.
// Callers map pgx.ErrNoRows to their own "not found" error.
func scanIncident(row pgx.Row) (*incident.Incident, error) {
	var inc incident.Incident

	err := row.Scan(
		&inc.ID,
		&inc.Title,
		&inc.Severity,
		&inc.Status,
		&inc.ChatID,
		&inc.TopicID,
		&inc.CreatedBy,
		&inc.CreatedAt,
		&inc.ClosedAt,
		&inc.TelegraphURLs,
		&inc.ReportURL,
	)
	if err != nil {
		return nil, err
	}

	return &inc, nil
}
